language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - "pip install -r travis_requirements.txt"
  - "python setup.py install"
# command to run tests
script: coverage run --source=datatables -m pytest -v
after_success: coveralls
